version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - "4080:80"
    volumes:
      - ./html:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

  php:
    image: php:7.3-fpm
    volumes:
      - .:/code
    networks:
      - web

networks:
  web:
    driver: bridge
